#!/bin/bash
#SBATCH --job-name=vasp_phonon
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=44
#SBATCH --mem=180G
#SBATCH --partition=short
#SBATCH --time=12:00:00
#SBATCH --constraint=64c

# --- Load correct VASP environment for this cluster ---
module purge
module load intel-oneapi-compilers/2025.0.4
module load intel-oneapi-mkl/2024.2.2
module load intel-oneapi-mpi/2021.14.1

# --- MPI / threading settings (keep from working script) ---
export OMP_NUM_THREADS=1
export I_MPI_HYDRA_BOOTSTRAP=slurm
export I_MPI_PIN_DOMAIN=core
export VASP_PATH=/projects/twist2d/modules/vasp/vasp.6.5.1/bin
ulimit -s unlimited

# We assume INCAR, KPOINTS, POTCAR are already in this directory.
# INCAR MUST be a static single-point (IBRION=-1, NSW=0, etc.)
# No relaxation! We only want forces on the displaced g
cd "$SLURM_SUBMIT_DIR"

# --- Run VASP single-point force calculation ---
mpirun $VASP_PATH/vasp_std
