#!/usr/bin/env python3
"""
Run-variant switch for the whole pipeline (``TWIST_VARIANT`` environment variable).

The workflow hardcodes the names of its generated directories relative to the repo
root (``monolayer_examples/``, ``phonopy_bilayer_examples/``, ``FINAL_RESULTS/`` ...)
and reads its host-local VASP templates from ``common/relaxation_templates/`` and
``common/staticpoint_templates/``. A *variant* lets a second, independent campaign
(e.g. bare PBE without the D3 correction) run from the same checkout without
touching the production tree:

    unset TWIST_VARIANT            -> exactly the historical paths, byte for byte
    export TWIST_VARIANT=bare_pbe  -> monolayer_examples_bare_pbe/, FINAL_RESULTS_BARE_PBE/,
                                      common/relaxation_templates_bare_pbe/, data/job_registry_bare_pbe.json, ...

Rules:
  * variant names are lowercase ``[a-z0-9_]`` so the suffix is well defined;
    upper-case directory names (FINAL_RESULTS) get the suffix upper-cased.
  * suffixing is idempotent: a name that already carries the suffix is returned unchanged.
  * ``FINAL_RESULTS_HEALTHY`` (hand-curated) and tracked inputs (``data/batches``,
    ``data/*overrides*.json``, ``template_structures/``) are deliberately NOT variant-aware.
  * the active variant is announced once on stderr so a stray export is visible.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ENV_VAR = "TWIST_VARIANT"
WORKFLOW_ROOT = Path(__file__).resolve().parent.parent

# Directory names (relative to the repo root) that are generated by the pipeline and
# therefore get the variant suffix. Kept for documentation / cleanup tooling.
GENERATED_DIRS = (
    "monolayer_examples",
    "bilayer_examples",
    "phonopy_monolayer_examples",
    "phonopy_bilayer_examples",
    "FINAL_RESULTS",
)

_VALID = re.compile(r"^[a-z0-9][a-z0-9_]*$")
_announced = False


def variant() -> str:
    """Active variant name ('' when TWIST_VARIANT is unset or empty)."""
    global _announced
    raw = os.environ.get(ENV_VAR, "").strip()
    if not raw:
        return ""
    if not _VALID.match(raw):
        raise ValueError(
            f"{ENV_VAR}={raw!r} is not a valid variant name (use lowercase letters, digits, '_')"
        )
    if not _announced:
        _announced = True
        print(
            f"[{ENV_VAR}={raw}] generated dirs get suffix '_{raw}', templates from "
            f"common/*_templates_{raw}/, registry data/job_registry_{raw}.json",
            file=sys.stderr,
        )
    return raw


def suffix_for(name: str) -> str:
    """Suffix to append to `name` ('' without a variant); upper-cased for upper-case names."""
    v = variant()
    if not v:
        return ""
    return "_" + (v.upper() if name.isupper() else v)


def variant_name(name: str) -> str:
    """`name` with the variant suffix applied (idempotent; unchanged without a variant)."""
    sfx = suffix_for(name)
    if not sfx or name.endswith(sfx):
        return name
    return name + sfx


def generated_dir(name: str, root: Path | None = None) -> Path:
    """Repo-root path of a generated directory, e.g. generated_dir('monolayer_examples')."""
    base = WORKFLOW_ROOT if root is None else Path(root)
    return base / variant_name(name)


def templates_dir(kind: str) -> Path:
    """common/<kind>_templates[_<variant>]/ for kind in {'relaxation', 'staticpoint'}."""
    if kind not in ("relaxation", "staticpoint"):
        raise ValueError(f"Unknown template kind: {kind!r}")
    return WORKFLOW_ROOT / "common" / variant_name(f"{kind}_templates")


def registry_path() -> Path:
    """data/job_registry[_<variant>].json"""
    v = variant()
    return WORKFLOW_ROOT / "data" / (f"job_registry_{v}.json" if v else "job_registry.json")
